### get all users

GET http://localhost:3000/students

### add new student
POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "ihor",
  "email": "ihor@gmail.com"
}

### get specific user
GET http://localhost:3000/students/942234